# Generated by Django 4.1.7 on 2023-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'лого',
                'verbose_name_plural': 'Лого',
                'ordering': ['id'],
            },
        ),
    ]
