# Generated by Django 4.1.7 on 2023-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Parking', models.IntegerField(verbose_name='Деректер базасындағы паркинг номері')),
                ('number', models.IntegerField(verbose_name='Паркингтегі бос орын саны')),
            ],
            options={
                'verbose_name': 'Паркинг',
                'verbose_name_plural': 'Паркинг',
                'ordering': ['id'],
            },
        ),
    ]
